apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  caas.fr/environment: prod
patchesStrategicMerge:
- replicas.yaml
- env.yaml
resources:
- ../../base
images:
- name: nginx
  newName: "herveleclerc/nginx"
  newTag: "1.19.9"
- name: herveleclerc/nginx
  newTag: 1.23.1
