apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: herveleclerc/nginx:^1.x
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: kustomization
  name: update-image-poc
  namespace: argocd
spec:
  destination:
    namespace: image-upd-poc
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/overlays/prod
    repoURL: https://github.com/herveleclerc/argo-img-updater.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
